-- TABLE
CREATE TABLE "Cliente" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NOME"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"TELEFONE"	INTEGER
);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
